version: '3.8'

services:
  perpustakaan:
    build: .
    ports:
      - "9091:9091"
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/perpustakaan
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - GRPC_SERVER_PORT=9091
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: perpustakaan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
